spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=GMT%2b8&autoReconnect=true&failOverReadOnly=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    rest:
      uris: ${ES_URIS}
      username: ${ES_USERNAME}
      password: ${ES_PASSWORD}

MYSQL_DB: test
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_USERNAME: root
MYSQL_PASSWORD: 1qaz2wsx

#ES_URIS: 114.115.233.237:9200
#ES_USERNAME: elastic
#ES_PASSWORD: 5WASSui4CPrRJ1HUgVRa